# Generated by Django 3.0.5 on 2020-04-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkgId', models.IntegerField(default=0)),
                ('whId', models.IntegerField(default=0)),
                ('whX', models.IntegerField(default=0)),
                ('whY', models.IntegerField(default=0)),
                ('buyerX', models.IntegerField(default=0)),
                ('buyerY', models.IntegerField(default=0)),
                ('upsId', models.CharField(default='', max_length=200, null=True)),
                ('truckId', models.IntegerField(default=0)),
                ('productStatus', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckId', models.IntegerField(default=0)),
                ('truckX', models.IntegerField(default=0)),
                ('truckY', models.IntegerField(default=0)),
                ('truckStatus', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField(default=0)),
                ('productDescrip', models.CharField(default='', max_length=200, null=True)),
                ('productCount', models.IntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups.Package')),
            ],
        ),
    ]
