# Generated by Django 3.0.5 on 2020-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='pkgId',
            field=models.IntegerField(default=0),
        ),
    ]
