# Generated by Django 3.0.5 on 2020-04-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0002_truck_pkgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='buyerX',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='package',
            name='buyerY',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='package',
            name='pkgId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='package',
            name='truckId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='package',
            name='whId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='package',
            name='whX',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='package',
            name='whY',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCount',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='truck',
            name='pkgId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truckId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truckX',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truckY',
            field=models.IntegerField(default=-1),
        ),
    ]
