# Generated by Django 3.0.5 on 2020-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0003_auto_20200420_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='id',
        ),
        migrations.AlterField(
            model_name='package',
            name='pkgId',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
