# Generated by Django 3.1.3 on 2020-11-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0005_post'),
        ('ups', '0005_doctors_wmusers'),
    ]

    operations = [
    ]
